### ISSUE TITLE
DNSDirector sets dynamic DNS to 'off' 

### ISSUE THREAD

**Issue by pwil** [kalahari/DnsDirector#1] opened 2016-04-15 17:36 UTC
When DNSD runs, its modification of the DNS list causes Windows to set the network's Dynamic DNS setting to 'manual'.  This means that the network interface will use whatever the last known dns servers were.  If those servers are internal corporate network dns servers, and you are now outside of that network (and not on a vpn), you will be unable to reach internet servers by name.
Maybe on shutdown, DNSD should restore the 'automatic' state for dynamic DNS if it was originally set that way?  There are ways to handle this in the config, having public dns as the fallback, but then you have to know all the internal domain names that need rules.

**Comment by kalahari** [comment] 2016-04-17 00:46
OK, so the issue is this: DnsDirector has to add localhost as the first DNS resolver in order to proxy DNS requests. However, doing this make DNS server configuration manual even if it was automatic (DHCP) before, and if you move to a different network, the DNS resolvers will not be updated.

**Comment by kalahari** [comment] 2016-04-17 01:28
The solution is twofold. First, when DnsDirector stops/exits, all interfaces with DHCP enabled are set to automatically obtain DNS servers. Second, when DnsDirector starts, or receives a network configuration changed event, it will set the the adapter to automatically obtain DNS servers just long enough to establish what the default DNS servers should be. Then it will insert itself back in at the top of the DNS server list.

**Comment by kalahari** [comment] 2016-04-17 02:11
This should be fixed in the 1.2 release: https://github.com/kalahari/DnsDirector/releases/tag/v1.2

**Comment by kalahari** [comment] 2016-04-21 04:53
Fix is working well in the field

**Closed as completed by kalahari** 2016-04-21 04:53 UTC
Labels: bug
